version: '3.9'
services:
    client:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '443:3000'
        environment:
            - VITE_API_URL=${VITE_API_URL}
